module.exports = {
  results: [
    {
      jobId: 39358618,
      employerId: 372124,
      employerName: "4Leisure Recruitment",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Golf & Event Sales - 3 days per week ",
      locationName: "Redbourn",
      minimumSalary: 12000,
      maximumSalary: 18000,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " Golf &amp; Event Sales Executive - near St Albans I am recruiting on behalf of a multi-faceted, high profile Golf Club in the St Albans area for an experienced Golf &amp; Event Sales Executive - part-time 3 days per week. The client is a well-established business with a superb reputation and they are looking for a proactive and dynamic individual to take ownership of the sales arm of the club. You will be respo... ",
      applications: 0,
      jobUrl:
        "https://www.reed.co.uk/jobs/golf-event-sales-3-days-per-week/39358618"
    },
    {
      jobId: 39358617,
      employerId: 400531,
      employerName:
        "Morgan Radley Finance & Automotive Recruitment Specialists ",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Vehicle Technician",
      locationName: "Wembley",
      minimumSalary: 26000,
      maximumSalary: 34000,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " Are you a highly experienced and dedicated Vehicle Technician with LCV experience? Do you possess extensive automotive knowledge? Our client a successful motor retail group are offering the right Vehicle Technician a highly competitive salary package, uncapped  bonus scheme and one of the best manufacturer training programs' in the UK! When joining this very successful motor retail group you will also benefit from a clear development and pro... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/vehicle-technician/39358617"
    },
    {
      jobId: 39358616,
      employerId: 582924,
      employerName: "Hamilton Cross",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Care Assistant",
      locationName: "Sheffield",
      minimumSalary: 9,
      maximumSalary: 18,
      currency: "GBP",
      expirationDate: "11/12/2019",
      date: "13/11/2019",
      jobDescription:
        " WANT TO EARN &#163;350 to &#163;650 PER WEEK AS AN&nbsp;AGENCY CARER / CARE ASSISTANT / SUPPORT WORKER? ** LOTS OF WORK AVAILABLE TO CHOOSE FROM EVERY WEEK ** HAMILTON CROSS Agency Carers / HCAs regularly earn in excess of &#163;500 per week undertaking flexible shifts that suit them, with lots of work available. Agency Carer rates: &#163;... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/care-assistant/39358616"
    },
    {
      jobId: 39358615,
      employerId: 468848,
      employerName: "CB Resourcing Ltd",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Intranet Co-ordinator",
      locationName: "City of London",
      minimumSalary: null,
      maximumSalary: null,
      currency: null,
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " A leading global law firm has a new 6 month contract for an Intranet Coordinator to work in their London office. Reporting to the Intranet and Knowledge Systems Manager, the successful candidate will have responsibility for the day to day maintenance of  the firm’s international intranet and other UK knowledge systems, including the firm’s SharePoint based database. Working collaboratively across many teams within the business... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/intranet-co-ordinator/39358615"
    },
    {
      jobId: 39358614,
      employerId: 15606,
      employerName: "Grapevine Recruitment",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Waste Site Operative - Canvey",
      locationName: "Canvey Island",
      minimumSalary: 8.7,
      maximumSalary: 8.7,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " Grapevine Recruitment are pleased to be working alongside a blue chip company based in Canvey. We are looking for 15 waste site operatives to start asap You will be providing assistance to the public and there is some lifting involved and standing for long periods of time, so the successful candidates must be physically fit. You must have excellent communication skills as you will be working alongside members of the publ... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/waste-site-operative-canvey/39358614"
    },
    {
      jobId: 39358613,
      employerId: 418809,
      employerName: "Gleeson Recruitment Group",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Accounts Receivable/Cashier",
      locationName: "Sutton Coldfield",
      minimumSalary: 11,
      maximumSalary: 12,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " A fantastic opportunity temporary opportunity for a Accounts Receivable/Cashier Assistant to join a large reputable organisation near Coleshill. The role is initially a 3 month temporary contract.  Key responsibilities will be the processing and reconciling of payments, chip &amp; pin transactions, corporate cards and petty cash. Liaising with centres regarding their banking's and resolving any queries / discrepancies. Month end journ... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/accounts-receivable-cashier/39358613"
    },
    {
      jobId: 38656243,
      employerId: 206996,
      employerName: "Haybrook IT Resourcing Ltd",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Full Stack Software Engineer ",
      locationName: "Oxford",
      minimumSalary: 40000,
      maximumSalary: 65000,
      currency: "GBP",
      expirationDate: "13/12/2019",
      date: "09/08/2019",
      jobDescription:
        " Software Developer  Are you a Software Developer looking to join an ambitious consultancy environment?  Are you interested in data driven approaches to solution design, perhaps implementing machine learning technologies?  A consultancy with firm roots in Oxford’s tech scene is looking for Senior and Mid-level Software Engineers as their team expands to meet their business needs.  <p... ",
      applications: 8,
      jobUrl:
        "https://www.reed.co.uk/jobs/full-stack-software-engineer/38656243"
    },
    {
      jobId: 39296768,
      employerId: 543104,
      employerName: "Jobheron ",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Chef de Partie",
      locationName: "London",
      minimumSalary: 30000,
      maximumSalary: 40000,
      currency: "GBP",
      expirationDate: "17/12/2019",
      date: "05/11/2019",
      jobDescription:
        " A busy Italian Restaurant in the heart of Knightsbridge has an exciting opportunity for an experienced Chef de Partie to join their vibrant, successful, and passionate team. Blessed with a prime location in one of the most prestigious areas of London alongside a loyal customer base of regular clientele as well as a strong influx of out-of-town visitors, this successful restaurant is well known for its exceptional but casual  dining sc... ",
      applications: 1,
      jobUrl: "https://www.reed.co.uk/jobs/chef-de-partie/39296768"
    },
    {
      jobId: 39296767,
      employerId: 443312,
      employerName: "rthirteen recruitment",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle:
        "Project Manager, Immediate Start, Norwich, £35,000 - £50,000 DOE  ",
      locationName: "Norwich",
      minimumSalary: 35000,
      maximumSalary: 50000,
      currency: "GBP",
      expirationDate: "17/12/2019",
      date: "05/11/2019",
      jobDescription:
        " Are you in search of a challenging yet varied project management opportunity? R13 recruitment are working in partnership with a unique, market leading organisation in their search for a Project Manager to join their team in the North West of Norwich. This is a growing company that had much success in the last fears years due to their  quality products, market knowledge and excellent brand reputation. Joining in this highly varied role... ",
      applications: 21,
      jobUrl:
        "https://www.reed.co.uk/jobs/project-manager-immediate-start-norwich-35000-50000-doe/39296767"
    },
    {
      jobId: 39358612,
      employerId: 543961,
      employerName: "MegaNexus Ltd",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Senior Accountant",
      locationName: "Central London",
      minimumSalary: null,
      maximumSalary: null,
      currency: null,
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " MegaNexus is the global leader in software which supports the rehabilitation of vulnerable people. We delivery hundreds of solutions on a single technology platform to a range of public, private and third sector service providers. We work  primarily across Justice, Healthcare and Community sectors. We are looking for an exceptional, ambitious Accountant to join our London team. This is a broad role, r... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/senior-accountant/39358612"
    },
    {
      jobId: 39296765,
      employerId: 603623,
      employerName: "Renaissance Care (Scotland) Ltd",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Maintenance Person Bank Shifts",
      locationName: "Uddingston",
      minimumSalary: null,
      maximumSalary: null,
      currency: null,
      expirationDate: "17/12/2019",
      date: "05/11/2019",
      jobDescription:
        " We are seeking caring and talented individuals who will make a difference to the lives of our residents. We are seeking an experienced Maintenance Person for a bank position in our Rosepark Nursing Home. Please note also that this is not a full or part time position. Shifts will be allocated on an 'as and when required' basis to cover instances of staff holidays, sickness or shortages. <... ",
      applications: 3,
      jobUrl:
        "https://www.reed.co.uk/jobs/maintenance-person-bank-shifts/39296765"
    },
    {
      jobId: 39358611,
      employerId: 602011,
      employerName: "Advanced Resource Managers Limited",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Bridge Engineer",
      locationName: "Doncaster",
      minimumSalary: 28,
      maximumSalary: 30,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " Bridge Engineer  Fantastic opportunity for an Experienced Bridge Engineer to join an excellent organisation in South Yorkshire on a contract basis, initially running for 6 months with potential to be extended.  In this role you will:  Initiate, develop, manage and deliver structures projects and works programmes (both individual and multi-structure) to time and budget.Co-or... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/bridge-engineer/39358611"
    },
    {
      jobId: 39274421,
      employerId: 424608,
      employerName: "Bennett & Game Recruitment",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Business Development Manager / Sales Manager",
      locationName: "Buckinghamshire",
      minimumSalary: 40000,
      maximumSalary: 40000,
      currency: "GBP",
      expirationDate: "13/12/2019",
      date: "01/11/2019",
      jobDescription:
        " Business Development Manager / Sales Manager required for our client; a leading Water Treatment company in Buckinghamshire. They require an experienced Business Development Manager to join their team and assist with the growth of the business  by selling their Water Treatment products to consultants, M&#43;E contractors, builder's merchants and end users across the South East. Business Development Manager</str... ",
      applications: 3,
      jobUrl:
        "https://www.reed.co.uk/jobs/business-development-manager-sales-manager/39274421"
    },
    {
      jobId: 39274420,
      employerId: 373216,
      employerName: "Freightserve",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Airfreight Pricing Coordinator",
      locationName: "Heathrow",
      minimumSalary: null,
      maximumSalary: null,
      currency: null,
      expirationDate: "13/12/2019",
      date: "01/11/2019",
      jobDescription:
        " Freightserve recruitment are looking for an experienced Airfreight Pricing person. The company are major Heathrow based Freight Forwarder. Job Description:- The Purpose of Sales Support Executive is to provide a product that delights the customers and the sales team, where customers (both internal and external) are satisfied, financial targets are met and hopefully exceeded. The most suitable candidate will  ne... ",
      applications: 6,
      jobUrl:
        "https://www.reed.co.uk/jobs/airfreight-pricing-coordinator/39274420"
    },
    {
      jobId: 39186610,
      employerId: 2763,
      employerName: "ADLIB",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Performance Marketing Manager",
      locationName: "Bristol",
      minimumSalary: 35000,
      maximumSalary: 45000,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "21/10/2019",
      jobDescription:
        "  Global, innovative Media, Tech and Games business new on the Bristol scene.Play a key role in the brand new Digital Acquisition team.Amazing benefits on offer. I’m working with an impressive media and tech company with a focus on gaming who are in the process of relocating their digital acquisition team from San Francisco to Bristol. These guys operate... ",
      applications: 5,
      jobUrl:
        "https://www.reed.co.uk/jobs/performance-marketing-manager/39186610"
    },
    {
      jobId: 39274419,
      employerId: 524744,
      employerName: "Hays Specialist Recruitment Limited",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Support Worker - Learning Difficulties",
      locationName: "Llantwit Major",
      minimumSalary: 8,
      maximumSalary: 12,
      currency: "GBP",
      expirationDate: "29/11/2019",
      date: "01/11/2019",
      jobDescription:
        " Llantwit Major- Learning Difficulties Support Worker - ASAP Start Support Worker - Llantwit MajorHays Social Care are working with some outstanding providers within Swansea and the surrounding areas, providing vulnerable individuals with practical and emotional care, enabling them to have fulfilled lives and gain further independence.We work with children and young adults with learning disabilities, mental... ",
      applications: 0,
      jobUrl:
        "https://www.reed.co.uk/jobs/support-worker-learning-difficulties/39274419"
    },
    {
      jobId: 39274418,
      employerId: 435121,
      employerName: "Armstrong Evans",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Stairlift Engineer",
      locationName: "Newark",
      minimumSalary: 23000,
      maximumSalary: 26000,
      currency: "GBP",
      expirationDate: "13/12/2019",
      date: "01/11/2019",
      jobDescription:
        " My client is a leading specialist in the field of mobility engineering, providing solutions in the form of stairlifts, ramps, hoists and platform lifts throughout East Midlands.  They’re currently seeking an experienced Stairlift &amp; Mobility Engineer to cover the areas of Lincolnshire and Nottinghamshire to join their growing family of employees.  The role for the Stairlift Engineer will involve;   The new instal... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/stairlift-engineer/39274418"
    },
    {
      jobId: 39358610,
      employerId: 316119,
      employerName: "G2 Legal Limited",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Company Secretarial Assistant",
      locationName: "London",
      minimumSalary: 25000,
      maximumSalary: 32000,
      currency: "GBP",
      expirationDate: "11/12/2019",
      date: "13/11/2019",
      jobDescription:
        "My client is a leading provider of corporate and fund services that have a global presence. They are now looking for a junior company secretarial assistant to join their expanding Company Secretarial team based in London. The role will be on a ten-month fixed term contract, working in a fast-paced and international environment.As a company secretarial assistant, your responsibilities will include managing a po... ",
      applications: 0,
      jobUrl:
        "https://www.reed.co.uk/jobs/company-secretarial-assistant/39358610"
    },
    {
      jobId: 39358609,
      employerId: 414284,
      employerName: "Klein Hamilton Legal & Finance Recruitment",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Residential Conveyancing Paralegal",
      locationName: "Central London",
      minimumSalary: 24000,
      maximumSalary: 26000,
      currency: "GBP",
      expirationDate: "11/12/2019",
      date: "13/11/2019",
      jobDescription:
        "Residential Conveyancing ParalegalREF: YK1875Salary: &#163;24,000 - &#163;26,000 Location: Central London Job Type: Full TimeJob Section: Private PracticeExperience: 1 years’ experience Contact: Yoned KhanCompany Benefits: City Firm, Bonus StructureCentral London Law Firm specialising in Property, Conveyancing, Wills &amp; Probate and Family Law seeks experienced Residential Conve... ",
      applications: 0,
      jobUrl:
        "https://www.reed.co.uk/jobs/residential-conveyancing-paralegal/39358609"
    },
    {
      jobId: 39274417,
      employerId: 60987,
      employerName: "Law Staff Legal Recruitment",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Associate - Corporate",
      locationName: "Jersey",
      minimumSalary: null,
      maximumSalary: null,
      currency: null,
      expirationDate: "13/12/2019",
      date: "01/11/2019",
      jobDescription:
        "Skilful Corporate Associate sought for a prestigious, Legal 500 firm in Jersey on a full-time, permanent basis. Joining our client’s thriving practice located in Jersey, the successful applicant will use their expertise to handle a complex caseload of corporate matters. A desire to get involved with a variety of transactional matters is essential for this role. Responsibilities • Mergers and acquisitions • Adv... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/associate-corporate/39274417"
    },
    {
      jobId: 39358608,
      employerId: 514667,
      employerName: "Greencore",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Despatch Coordinator Night Shift",
      locationName: "Boston",
      minimumSalary: null,
      maximumSalary: null,
      currency: null,
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " It’s the responsibility for our Night Shift Despatch Coordinator to ensure our teams not only deliver but implement service improvements which meet customer requirements and ensure we comply with food safety legislation.  Taking ownership for product quality in the day to day running of the Despatch and area.Ensuring good communications are maintained within the area and good communications are maintained with other depa... ",
      applications: 0,
      jobUrl:
        "https://www.reed.co.uk/jobs/despatch-coordinator-night-shift/39358608"
    },
    {
      jobId: 39296764,
      employerId: 369004,
      employerName: "First Choice Staff",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Accounts Clerk x2 ",
      locationName: "Heathrow",
      minimumSalary: 21000,
      maximumSalary: 25000,
      currency: "GBP",
      expirationDate: "17/12/2019",
      date: "05/11/2019",
      jobDescription:
        " We require a confident and passionate individuals to take on the position of &quot;Accounts Assistant&quot; for a market leader in Gateway Logistics and ecommerce solutions. To Support the Accounting team with all aspects of daily duties to ensure the efficient running  of the department, in-order-to meet month end reporting deadlines. Duties &amp; Responsibilities: Submit daily CAD’s (Courier Accounting Documentation) <br... ",
      applications: 35,
      jobUrl: "https://www.reed.co.uk/jobs/accounts-clerk-x2/39296764"
    },
    {
      jobId: 39296763,
      employerId: 602011,
      employerName: "Advanced Resource Managers Limited",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Software Developer .Net",
      locationName: "Basingstoke",
      minimumSalary: null,
      maximumSalary: null,
      currency: null,
      expirationDate: "17/12/2019",
      date: "05/11/2019",
      jobDescription:
        " Software Developer .Net -Basingstoke Our client a leading ID Solutions provider are looking for a Software Developer with strong .Net experience to strengthen their team based at their recently acquired HO in Basingstoke. The Software Development (SD) function at IDGS, provides mature agile development services for multiple customers and internal stakeholders, across a range of key software products across the business. ... ",
      applications: 1,
      jobUrl: "https://www.reed.co.uk/jobs/software-developer-net/39296763"
    },
    {
      jobId: 39358607,
      employerId: 524744,
      employerName: "Hays Specialist Recruitment Limited",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "SAP Applications Support Analyst",
      locationName: "Alton",
      minimumSalary: 20000,
      maximumSalary: 35000,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " SAP Applications Support Analyst - Alton - Up to &#163;35,000 Your new companyWe're currently recruiting for a retail business based in Alton who are looking for an IT Support Technician to join their IT Service Desk Team which supports over 150 users.Your new roleYou will be responsible for first line IT support via the help desk system and service desk calls as well as d... ",
      applications: 0,
      jobUrl:
        "https://www.reed.co.uk/jobs/sap-applications-support-analyst/39358607"
    },
    {
      jobId: 39358606,
      employerId: 94976,
      employerName: "White Knight Recruitment Ltd",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Support Worker",
      locationName: "Seaton",
      minimumSalary: 17800,
      maximumSalary: 17800,
      currency: "GBP",
      expirationDate: "11/12/2019",
      date: "13/11/2019",
      jobDescription:
        " SUPPORT WORKERS - RESIDENTIAL HOME - SEATON, DEVON - &#163;17,800 - 12 HOUR SHIFTS - DAYS AND NIGHTS AVAILABLE White Knight are delighted to be recruiting for Support Workers to join a lovely residential home based in Seaton. This is an excellent opportunity for experienced Support Workers to work with a lovely provider. The successful Support Worker will have the  following responsibilities:  Provide the ... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/support-worker/39358606"
    },
    {
      jobId: 39358605,
      employerId: 575264,
      employerName: "REED",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Tax Manager",
      locationName: "Southampton",
      minimumSalary: 40000,
      maximumSalary: 55000,
      currency: "GBP",
      expirationDate: "13/12/2019",
      date: "13/11/2019",
      jobDescription:
        " An amazing opportunity is now available for a qualified and experienced Tax Manager to join my client In Southampton. The ideal candidate will be ACA / ACCA / ATT or CTA qualified and will have a proven track record of specialising in tax. You should have a strong career history that shows clear progression and a good track record in finance. This role will require at least 4 years’ experience specifically in tax. This is an am... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/tax-manager/39358605"
    },
    {
      jobId: 39274416,
      employerId: 400666,
      employerName: "CVWOW",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Electrical / Mechanical Technician",
      locationName: "Livingston",
      minimumSalary: 30000,
      maximumSalary: 32000,
      currency: "GBP",
      expirationDate: "13/12/2019",
      date: "01/11/2019",
      jobDescription:
        " Our client recruiting an Electrical or Mechanical Technician Location – Livingstone Our client are recruiting an Electrical or Mechanical Technician to join the team in Aberdeen. In this position you will be traveling around their sites working with one other, within a department of 6 teams, installing components, reporting, maintaining  and fault finding on Our client turbines.  As an Electrical / Mechanic... ",
      applications: 2,
      jobUrl:
        "https://www.reed.co.uk/jobs/electrical-mechanical-technician/39274416"
    },
    {
      jobId: 39358604,
      employerId: 575264,
      employerName: "REED",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Tax Manager",
      locationName: "Southampton",
      minimumSalary: 40000,
      maximumSalary: 55000,
      currency: "GBP",
      expirationDate: "13/12/2019",
      date: "13/11/2019",
      jobDescription:
        " An amazing opportunity is now available for a qualified and experienced Tax Manager to join my client In Southampton. The ideal candidate will be ACA / ACCA / ATT or CTA qualified and will have a proven track record of specialising in tax. You should have a strong career history that shows clear progression and a good track record in finance. This role will require at least 4 years’ experience specifically in tax. This is an am... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/tax-manager/39358604"
    },
    {
      jobId: 39296762,
      employerId: 524744,
      employerName: "Hays Specialist Recruitment Limited",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "PTP Query Administrator",
      locationName: "Manchester",
      minimumSalary: 11,
      maximumSalary: 12,
      currency: "GBP",
      expirationDate: "03/12/2019",
      date: "05/11/2019",
      jobDescription:
        " A multinational consumer goods company based in Manchester is looking for a PTP Querying Clerk paying &#163;11-&#163;12 Your new companyBased in North Manchester your new company is a market leader in their industry working with household names across the globe. They boast revenues above the &#163;100 Million mark. Due to staff illness they are looking for an experienced PTP Queries Administrator  to join t... ",
      applications: 4,
      jobUrl: "https://www.reed.co.uk/jobs/ptp-query-administrator/39296762"
    },
    {
      jobId: 39274415,
      employerId: 359553,
      employerName: "SER (Staffing) Ltd",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Drainage Design Engineer",
      locationName: "Mold",
      minimumSalary: 25000,
      maximumSalary: 30000,
      currency: "GBP",
      expirationDate: "13/12/2019",
      date: "01/11/2019",
      jobDescription:
        " Position - Drainage Design Engineer Location - Mold Salary/Package - &#163;25,000 to &#163;30,000, 21 days Hol &#43; Stat, Pension, Expenses &amp; Annual Bonus  My Client are an Independent Consultancy who specialise in Flood Risk, Drainage, Water Management &amp; Utilities. Established for over 20 years, and very well regarded, services include Flood Risk Assessm... ",
      applications: 1,
      jobUrl: "https://www.reed.co.uk/jobs/drainage-design-engineer/39274415"
    },
    {
      jobId: 39274414,
      employerId: 451665,
      employerName: "Cordant People",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Client Services Agent",
      locationName: "Coventry",
      minimumSalary: 8.88,
      maximumSalary: 8.88,
      currency: "GBP",
      expirationDate: "13/12/2019",
      date: "01/11/2019",
      jobDescription:
        " A fantastic temporary ongoing opportunity has arisen for Client Service Agents to join a fast paced team working within an amazing location for a Logistics company in Coventry.  The purpose of the role is to provide support to some of the business's largest clients, solving problems and ensuring the highest level of customer service. Daily Duties Include: * Taking telephone enquiries to and using the system to solve smal... ",
      applications: 6,
      jobUrl: "https://www.reed.co.uk/jobs/client-services-agent/39274414"
    },
    {
      jobId: 39358603,
      employerId: 575264,
      employerName: "REED",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Tax Manager",
      locationName: "Southampton",
      minimumSalary: 40000,
      maximumSalary: 55000,
      currency: "GBP",
      expirationDate: "13/12/2019",
      date: "13/11/2019",
      jobDescription:
        " An amazing opportunity is now available for a qualified and experienced Tax Manager to join my client In Southampton. The ideal candidate will be ACA / ACCA / ATT or CTA qualified and will have a proven track record of specialising in tax. You should have a strong career history that shows clear progression and a good track record in finance. This role will require at least 4 years’ experience specifically in tax. This is an am... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/tax-manager/39358603"
    },
    {
      jobId: 39358602,
      employerId: 385838,
      employerName: "Search Consultancy",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Coded Welder",
      locationName: "Sheffield",
      minimumSalary: null,
      maximumSalary: null,
      currency: null,
      expirationDate: "11/12/2019",
      date: "13/11/2019",
      jobDescription:
        " Coded Welders needed in Yorkshire &amp; MidlandsSearch consultancy construction team are looking for Coded Welders in the Yorkshire and Midlands area. Requirements:* References* Experience in this area* PPE* CSCS (Desirable) * Relevant Qualifications or Time Served* Must be able to read drawings* MMA Codings If you are free for work straight away and you are ... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/coded-welder/39358602"
    },
    {
      jobId: 39296761,
      employerId: 121141,
      employerName: "Future Select Ltd",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Water Hygiene Engineer - Birmingham",
      locationName: "Birmingham",
      minimumSalary: 30000,
      maximumSalary: 30000,
      currency: "GBP",
      expirationDate: "17/12/2019",
      date: "05/11/2019",
      jobDescription:
        "Our client, is a leading name within the water treatment/hygiene industry and they provide a wide range of legionella, water treatment and water hygiene services to national clients. They are currently recruiting for an experienced Water Hygiene Engineer  to cover a wide variety of contracts in and around the Birmingham area. Consideration will be given to applications from Coventry, Kidderminster, Stoke-on-Trent and the surrounding areas will b... ",
      applications: 0,
      jobUrl:
        "https://www.reed.co.uk/jobs/water-hygiene-engineer-birmingham/39296761"
    },
    {
      jobId: 39358601,
      employerId: 416048,
      employerName: "Pure 4 Recruitment Limited",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Merchandiser",
      locationName: "Cheadle Hulme",
      minimumSalary: 18000,
      maximumSalary: 20000,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " My client is an exciting and growing business who are now looking for a Merchandiser to join their energetic team. You will be responsible for the timely arrival of all stock into the company warehouse, direct to customer or delivered to customer on FOB sales terms. You will be reporting to the Supply Chain Team Leader and working closely with other colleagues based  at the head office maintaining close working relationships with manu... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/merchandiser/39358601"
    },
    {
      jobId: 39358600,
      employerId: 259047,
      employerName: "Recruiting UK",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "IFA / Wealth adviser- Glasgow",
      locationName: "Glasgow",
      minimumSalary: 45000,
      maximumSalary: 55000,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " IFA / Financial Planner - Glasgow Our Client is an established financial advice firm in Glasgow and are seeking to recruit a qualified financial planner/IFA to service and develop an existing large client bank. You would provide face to face advice across a range of Investments, Savings and Pension related with the successful applicant being an employed adviser with the responsibility for developing this portfo... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/ifa-wealth-adviser-glasgow/39358600"
    },
    {
      jobId: 39274413,
      employerId: 575264,
      employerName: "REED",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Youth Development Officer",
      locationName: "Vauxhall",
      minimumSalary: 14,
      maximumSalary: 14,
      currency: "GBP",
      expirationDate: "15/11/2019",
      date: "01/11/2019",
      jobDescription:
        " Have you worked with young audiences? Have experience of developing&nbsp;and maintaining&nbsp;stakeholder relationships? Have knowledge of the UK youth sector and experience of engaging via social media? Keep reading! My client is a charity based in Vauxhall and has an opening for a temporary Youth Development Officer. The role will begin Monday 11th November and run until March, full-time, 09:00-17:00&nbsp;Monday-Friday. Main ... ",
      applications: 9,
      jobUrl: "https://www.reed.co.uk/jobs/youth-development-officer/39274413"
    },
    {
      jobId: 39274412,
      employerId: 575264,
      employerName: "REED",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Youth Development Officer",
      locationName: "Vauxhall",
      minimumSalary: 14,
      maximumSalary: 14,
      currency: "GBP",
      expirationDate: "15/11/2019",
      date: "01/11/2019",
      jobDescription:
        " Have you worked with young audiences? Have experience of developing&nbsp;and maintaining&nbsp;stakeholder relationships? Have knowledge of the UK youth sector and experience of engaging via social media? Keep reading! My client is a charity based in Vauxhall and has an opening for a temporary Youth Development Officer. The role will begin Monday 11th November and run until March, full-time, 09:00-17:00&nbsp;Monday-Friday. Main ... ",
      applications: 5,
      jobUrl: "https://www.reed.co.uk/jobs/youth-development-officer/39274412"
    },
    {
      jobId: 39358599,
      employerId: 459971,
      employerName: "AdMore",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "E-Commerce Assistant Hair & Beauty",
      locationName: "Aylesbury",
      minimumSalary: 25000,
      maximumSalary: 28000,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " **E-Commerce Assistant (Hair &amp; Beauty) - Aylesbury - up to &#163;28k - Exciting, Fast-Growing Business**Are you an E-commerce/Content professional? Do you have an interest in the Hair &amp; Beauty industry? This is a fantastic opportunity for a creative and enthusiastic individual to join a fast-growing Hair &amp; Beauty business which has a great working culture.What does this E-Commerce Assistant (Hair &amp; Bea... ",
      applications: 0,
      jobUrl:
        "https://www.reed.co.uk/jobs/e-commerce-assistant-hair-beauty/39358599"
    },
    {
      jobId: 39274410,
      employerId: 520034,
      employerName: "Sanderson",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "IT Engineer",
      locationName: "Berkshire",
      minimumSalary: 35000,
      maximumSalary: 40000,
      currency: "GBP",
      expirationDate: "13/12/2019",
      date: "01/11/2019",
      jobDescription:
        " IT HELP DESK LEAD - Berkshire - &#163;40000 My Client is looking for an experienced IT Help Desk Lead to join the exoerienced IT Service team, Within the automative industry.  Experience with Leading Projects and managing a small to medium sized teams would put you in a great position to work for this great company,  Skills and experience :   Virtualisation Cluster Servers Pcs NAS <... ",
      applications: 6,
      jobUrl: "https://www.reed.co.uk/jobs/it-engineer/39274410"
    },
    {
      jobId: 39296760,
      employerId: 543509,
      employerName: "Excelcare Holdings",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Deputy Care Manager - Park Avenue Care Home",
      locationName: "Bromley",
      minimumSalary: 40000,
      maximumSalary: 45000,
      currency: "GBP",
      expirationDate: "17/12/2019",
      date: "05/11/2019",
      jobDescription:
        " Salary: Up to &#163;45,000 depending on experience and qualifications. This is an exciting opportunity for a Nurse Qualified Team Leader or Clinical Manager to take the next step to becoming Deputy Care Manager in one of our flagship nursing homes in Bromley.&nbsp; As a Deputy Care Manager you will be passionate about embedding quality clinical practices in line with CQC regula... ",
      applications: 0,
      jobUrl:
        "https://www.reed.co.uk/jobs/deputy-care-manager-park-avenue-care-home/39296760"
    },
    {
      jobId: 39296759,
      employerId: 520033,
      employerName: "Resource Management ",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "CASS Oversight Analyst",
      locationName: "Bristol",
      minimumSalary: null,
      maximumSalary: null,
      currency: null,
      expirationDate: "17/12/2019",
      date: "05/11/2019",
      jobDescription:
        " Parmenion is a rapidly growing, award winning technology and investments solutions business. We launched in 2007 with just a handful of staff. In the 11 years since, we have seen the company grow exponentially. We currently house our 200&#43; staff in a magnificent  open plan office near the waterfront in the vibrant city of Bristol. Our strength comes from seamlessly integrating three core disciplines, discretionary investment manage... ",
      applications: 1,
      jobUrl: "https://www.reed.co.uk/jobs/cass-oversight-analyst/39296759"
    },
    {
      jobId: 39274409,
      employerId: 575264,
      employerName: "REED",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Youth Development Officer",
      locationName: "Vauxhall",
      minimumSalary: 14,
      maximumSalary: 14,
      currency: "GBP",
      expirationDate: "15/11/2019",
      date: "01/11/2019",
      jobDescription:
        " Have you worked with young audiences? Have experience of developing&nbsp;and maintaining&nbsp;stakeholder relationships? Have knowledge of the UK youth sector and experience of engaging via social media? Keep reading! My client is a charity based in Vauxhall and has an opening for a temporary Youth Development Officer. The role will begin Monday 11th November and run until March, full-time, 09:00-17:00&nbsp;Monday-Friday. Main ... ",
      applications: 6,
      jobUrl: "https://www.reed.co.uk/jobs/youth-development-officer/39274409"
    },
    {
      jobId: 39274408,
      employerId: 560522,
      employerName: "DUNBAR EDUCATION RECRUITMENT LIMITED",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Year 3 Teacher",
      locationName: "Borehamwood",
      minimumSalary: 24373,
      maximumSalary: 40490,
      currency: "GBP",
      expirationDate: "13/12/2019",
      date: "01/11/2019",
      jobDescription:
        " Would you be interested in joining a happy and hardworking school in Borehamwood? Looking for a January start in a Year 3 teacher role?  Year 3 TeacherJanuary StartBorehamwood, HertfordshirePermanent Post Dunbar Education are currently recruiting for a Year 3 teacher for a primary school in Borehamwood to join them from January 2020. Their vision of the school is to give children a s... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/year-3-teacher/39274408"
    },
    {
      jobId: 39358598,
      employerId: 438976,
      employerName: "Randstad Inhouse",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Order Processor",
      locationName: "Telford",
      minimumSalary: 8.46,
      maximumSalary: 8.46,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " Order Processing Agent Are you looking for a role in order processing with full training provided? Do you have previous customer service or sales administration experience?  We have competitive pay rates and set shift patterns, in a clean and professional environment. You'll get weekly pay, scheduled shifts, paid holiday and training. Do you have a proactive and professional approach to your work? If yes, please apply today!</p... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/order-processor/39358598"
    },
    {
      jobId: 39358597,
      employerId: 481224,
      employerName: "Matt Burton ",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Operations Director",
      locationName: "London",
      minimumSalary: 80000,
      maximumSalary: 90000,
      currency: "GBP",
      expirationDate: "11/12/2019",
      date: "13/11/2019",
      jobDescription:
        " Operations Director London &#163;80,000 - &#163;90,000My client, a leading global insurance company, is seeking an experienced Operations Director to lead the claims management operations for one of their specialist service lines. The Operations Director is key in ensuring the quality of service delivery across the business unit and has responsibility for managi... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/operations-director/39358597"
    },
    {
      jobId: 39274407,
      employerId: 377106,
      employerName: "Robert Walters",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Assistant Accountant",
      locationName: "Halesowen",
      minimumSalary: 24000,
      maximumSalary: 28000,
      currency: "GBP",
      expirationDate: "29/11/2019",
      date: "01/11/2019",
      jobDescription:
        " A rarely available Assistant Accountant role has just become available at a leading, global business based in Rubery. A rarely available Assistant Accountant role has just become available at a leading, global business based in Rubery. Reporting directly into the Finance Manager, this role offers outstanding career progression and is an ideal move if you are wanted to step  into a leading business. Key Responsibilities of the A... ",
      applications: 30,
      jobUrl: "https://www.reed.co.uk/jobs/assistant-accountant/39274407"
    },
    {
      jobId: 39358596,
      employerId: 418296,
      employerName: "Gi Group",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Retail Merchandiser",
      locationName: "Prescot",
      minimumSalary: 10,
      maximumSalary: 10,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " Gi Group are currently working with a number of big brand retail partners in providing them with merchandising staff to help ensure their stores look the very best they can be to the general public, and we are looking to add a number of new staff members  to their teams in the Prescot area.Working in retail merchandising means that you play a vital part in the process in how the stores market their products to their customers.The... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/retail-merchandiser/39358596"
    },
    {
      jobId: 39274406,
      employerId: 404651,
      employerName: "Recruitment Genius",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Junior Backend Developer",
      locationName: "York",
      minimumSalary: 18000,
      maximumSalary: 20000,
      currency: "GBP",
      expirationDate: "13/12/2019",
      date: "01/11/2019",
      jobDescription:
        "This company are a leading UK training provider offering courses in M&amp;E Safe Systems of Work, Electrical Installations, Legionella training and more. They are looking for an enthusiastic and passionate person to join their Digital team.Responsibilities: Testing/Quality Assurance, Second Level Technical Support, Releasing bug fixes, Developing new features for existing systems, Expanding and building upon existing frameworks, Writ... ",
      applications: 2,
      jobUrl: "https://www.reed.co.uk/jobs/junior-backend-developer/39274406"
    },
    {
      jobId: 39274405,
      employerId: 613965,
      employerName: "Emerald Group",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "PR Manager (9 Month FTC)",
      locationName: "Bingley",
      minimumSalary: 35000,
      maximumSalary: 40000,
      currency: "GBP",
      expirationDate: "13/12/2019",
      date: "01/11/2019",
      jobDescription:
        " Would you be interested in joining an award-winning and innovative academic publisher?  We have an opportunity for a PR Manager to join us on a Fixed Term Contract (Maternity Cover) to deliver our 2020 PR strategy.  Who Are Emerald:  Emerald Group is a global learning organisation, with a presence in 130 countries worldwide. While its roots are in publishing, and bringing research to life, the Group's co... ",
      applications: 2,
      jobUrl: "https://www.reed.co.uk/jobs/pr-manager-9-month-ftc/39274405"
    },
    {
      jobId: 39274404,
      employerId: 440513,
      employerName: "Whurk Recruitment ",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Senior Buyer",
      locationName: "Oxfordshire",
      minimumSalary: 40000,
      maximumSalary: 45000,
      currency: "GBP",
      expirationDate: "29/11/2019",
      date: "01/11/2019",
      jobDescription:
        "Our client, an automotive manufacturer in Oxford, is recruiting for a Senior Buyer to join their team due to new contracts.As Senior Buyer, you will be responsible for procurement activities including supply chain development, integration of purchasing and inventory processes into the ERP system and the management of materials and inventory. Ideally you will have worked as a Tier 1 automotive supplier, or as a minimum, wi... ",
      applications: 7,
      jobUrl: "https://www.reed.co.uk/jobs/senior-buyer/39274404"
    },
    {
      jobId: 39358505,
      employerId: 477351,
      employerName: "Michael Page Marketing",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Director of Commercial Analysis",
      locationName: "Hayes",
      minimumSalary: 90000,
      maximumSalary: 95000,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " Partnering with Senior Leaders you will drive a data driven culture supporting business decisions with insight and analysis - global FMCG company. Client Details The Director of Commercial Analysis will be leading the BI function of a global multi site FMCG brand where you will add value to business partners. They have experienced exciting growth and is a supportive and inclusive environment. The role will base... ",
      applications: 0,
      jobUrl:
        "https://www.reed.co.uk/jobs/director-of-commercial-analysis/39358505"
    },
    {
      jobId: 39051982,
      employerId: 417855,
      employerName: "Anchor Trust",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Care Assistant (Days and Nights)  - Greenacres",
      locationName: "Godstone",
      minimumSalary: 9.16,
      maximumSalary: 9.78,
      currency: "GBP",
      expirationDate: "26/12/2019",
      date: "03/10/2019",
      jobDescription:
        " Job title: Care Assistant - No experience required - Greenacres, Banstead Rate of pay: &#163;9.16- &#163;9.78 per hour, depending on experience As a care assistant you will provide person centred care and support to assist residents to maintain their independence including personal care, meal times, and activities whilst also providing a listening ear to those who need it most. Anchor ha... ",
      applications: 2,
      jobUrl:
        "https://www.reed.co.uk/jobs/care-assistant-days-and-nights-greenacres/39051982"
    },
    {
      jobId: 39358595,
      employerId: 381343,
      employerName: "Ashdown Appointments",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "SOUS CHEF - new opening - fresh, seasonal cuisine -",
      locationName: "East Grinstead",
      minimumSalary: 26000,
      maximumSalary: 28000,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " SOUS CHEF - new opening - fresh, seasonal cuisine - &#163;28,000 -  An exciting opportunity to be part of this new restaurant opening at the beginning of December. There is a very talented Head Chef and he is looking for a strong Sous Chef to assist with the day to day running of the kitchen.  The menus will be modern European and everything made in house using fresh, seasonal produce. As Sous Chef you will be an integral part ... ",
      applications: 0,
      jobUrl:
        "https://www.reed.co.uk/jobs/sous-chef-new-opening-fresh-seasonal-cuisine/39358595"
    },
    {
      jobId: 39358594,
      employerId: 315707,
      employerName: "Harris Lord Recruitment",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Software Engineer",
      locationName: "Cambridge",
      minimumSalary: 25000,
      maximumSalary: 30000,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " Software Engineer An exciting and award winning Cambridge-based start-up are seeking a Software Engineer to work on an innovative range of products in the medtech area. With some remote work. Essential criteria:  At degree or equivalent in Computer Science, Information Engineering, Software Engineering, Statistics, Math or relevant subject. Other degree types considered with experie... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/software-engineer/39358594"
    },
    {
      jobId: 39296758,
      employerId: 451665,
      employerName: "Cordant People",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Drivers Mate",
      locationName: "Golborne",
      minimumSalary: 8.28,
      maximumSalary: 8.28,
      currency: "GBP",
      expirationDate: "17/12/2019",
      date: "05/11/2019",
      jobDescription:
        " Cordant People are recruiting for drivers mates to join our client in Golborne as they enter their busiest time of the year. This role is temporary ongoing with work in to next year! The Role:  Loading goods for customersChecking delivery routesCalling customers to inform of delivery timesEnsuring the highest level of customer service is providedCompleting necessary checks of prod... ",
      applications: 6,
      jobUrl: "https://www.reed.co.uk/jobs/drivers-mate/39296758"
    },
    {
      jobId: 39358593,
      employerId: 377450,
      employerName: "Gabbott Recruitment Online Limited",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Head of Conveyancing",
      locationName: "Warrington",
      minimumSalary: 35000,
      maximumSalary: 40000,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " Head of Conveyancing Solicitor Conveyancing FCILEX St Helens area &#163;35,000 to &#163;40,000 plus negotiable, full time flexible working hours, free parking, plus great benefits Head of Conveyancing with residential property experience required for established and progressive firm of Solicitors busy and expanding department with... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/head-of-conveyancing/39358593"
    },
    {
      jobId: 39296757,
      employerId: 316119,
      employerName: "G2 Legal Limited",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Family Solicitor",
      locationName: "Manchester",
      minimumSalary: 40000,
      maximumSalary: 50000,
      currency: "GBP",
      expirationDate: "03/12/2019",
      date: "05/11/2019",
      jobDescription:
        "A Legal 500 ranked family department within a well regarded forward-thinking firm in South Manchester is on the lookout for an experienced family solicitor.Your role as the family solicitor will be to manage a broad range of family/matrimonial cases which are all privately funded. This will include&nbsp;divorce, pre-nuptials, cohabitation disputes and financial arrangements. The department is seeing continued growth as is... ",
      applications: 1,
      jobUrl: "https://www.reed.co.uk/jobs/family-solicitor/39296757"
    },
    {
      jobId: 39296756,
      employerId: 405952,
      employerName: "Corr Recruitment",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Contract Consultant",
      locationName: "Bradley Stoke",
      minimumSalary: 20000,
      maximumSalary: 25000,
      currency: "GBP",
      expirationDate: "17/12/2019",
      date: "05/11/2019",
      jobDescription:
        "Corr Recruitment LTD is an independently owned leading Recruitment Agency established in 2001, we have offices in Newbury,&nbsp; Andover, London, Basigstoke, Bristol and Tamworth.We’re looking for dedicated, ambitious and talented Contract Consultant to join our successful team in Bristol.Main Responsibilities: developing a good understanding of managed clients, their industry, what... ",
      applications: 1,
      jobUrl: "https://www.reed.co.uk/jobs/contract-consultant/39296756"
    },
    {
      jobId: 39358592,
      employerId: 408300,
      employerName: "Lowri Beck Services ",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Meter Reader",
      locationName: "St. Albans",
      minimumSalary: 8.28,
      maximumSalary: 8.28,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " Lowri Beck Services is looking for individuals to join a growing team of Meter Readers, in the following postcode areas: AL, EN, WD, CM, HP Working within your home postcode location, you will be required to obtain accurate meter readings and inspect meters at customers’ properties, entering the details on a handheld device at each location, and providing excellent customer service to positively  represent the Lowri Beck image &amp; c... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/meter-reader/39358592"
    },
    {
      jobId: 39358591,
      employerId: 397447,
      employerName: "NJR Recruitment",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Commercial / Business Analyst",
      locationName: "Lancashire",
      minimumSalary: 25000,
      maximumSalary: 30000,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " Commercial / Business Analyst Manchester  &#163;25,000 - &#163;30,000 Excellent benefits &amp; flexi-time Are you a commercially astute analyst looking to join a global player and play a key role in a companies growth plan?  The successful candidate will be joining a highly successful and award winning distributor ... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/commercial-business-analyst/39358591"
    },
    {
      jobId: 39296754,
      employerId: 18885,
      employerName: "Coburg Banks Limited",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Franchise Business Manager",
      locationName: "Newcastle Upon Tyne",
      minimumSalary: 60000,
      maximumSalary: 70000,
      currency: "GBP",
      expirationDate: "03/12/2019",
      date: "05/11/2019",
      jobDescription:
        "Franchise Business ManagerCovering North England / ScotlandSalary up to &#163;70,000 &#43; Excellent BenefitsOne of the largest pizza companies in the world are looking to recruit an influential individual with extensive management experience in catering / retail, ideally multi-unit supervision within the franchise restaurant sector. Offering an attractive salary  plus ex... ",
      applications: 24,
      jobUrl: "https://www.reed.co.uk/jobs/franchise-business-manager/39296754"
    },
    {
      jobId: 39274402,
      employerId: 548101,
      employerName: "NHS Professionals",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "administrator",
      locationName: "Calmore",
      minimumSalary: 9.46,
      maximumSalary: 9.46,
      currency: "GBP",
      expirationDate: "13/12/2019",
      date: "01/11/2019",
      jobDescription:
        " Job Title and Grade: Adminitratior  Location/Trust: Southern health  Department Covered: In Patients ward  Pay Rates: &#163;9.46 Placement Ref/ID:31630 Are you interested in Temporary Part time work and available asap to start? You will gain nhs expereince! Working Mon - Fri - part time 25 hours a week, between 8.30a... ",
      applications: 19,
      jobUrl: "https://www.reed.co.uk/jobs/administrator/39274402"
    },
    {
      jobId: 39358590,
      employerId: 400659,
      employerName: "Love Success Recruitment",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Planned Maintenance Administrator - £22,000 - £24,000",
      locationName: "Central London",
      minimumSalary: 23000,
      maximumSalary: 24000,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " Planned Maintenance Administrator - &#163;22,000 - &#163;24,000 - Immediate   Our client, a retail maintenance provider is looking for a proactive, reliable administrator to join their rapidly growing team. This is a busy role that will best suit a candidate with excellent communication and interpersonal skills. Day to day the role  will involve being first point of contact for customers, scheduling appointments, and ... ",
      applications: 0,
      jobUrl:
        "https://www.reed.co.uk/jobs/planned-maintenance-administrator-22000-24000/39358590"
    },
    {
      jobId: 39296753,
      employerId: 357396,
      employerName: "Jenrick Commercial",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Software Tester",
      locationName: "Epsom",
      minimumSalary: 150,
      maximumSalary: 173,
      currency: "GBP",
      expirationDate: "03/12/2019",
      date: "05/11/2019",
      jobDescription:
        "Software Tester is urgently required for a leading, award winning company who are going through rapid expansion due to business success on an on-going temporary contract to start ASAP.We are looking for an experienced Software Tester to play an important role in the development of new upcoming projects, making sure it works exactly as it should.Because it's a technical role, it's useful to have a strong understanding of o... ",
      applications: 13,
      jobUrl: "https://www.reed.co.uk/jobs/software-tester/39296753"
    },
    {
      jobId: 39358589,
      employerId: 316119,
      employerName: "G2 Legal Limited",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Construction Solicitor",
      locationName: "Leicester",
      minimumSalary: 50000,
      maximumSalary: 70000,
      currency: "GBP",
      expirationDate: "11/12/2019",
      date: "13/11/2019",
      jobDescription:
        "Are you a construction solicitor who is looking to join a leading Legal 200 firm in central Leicester? Perhaps you are at the stage in your career where you are looking to take on the challenge of growing a new team?&nbsp;This is a fantastic opportunity to join an already established national law firm during a time of growth!&nbsp;This is a particularly interesting position as although the firm is recognised n... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/construction-solicitor/39358589"
    },
    {
      jobId: 39358588,
      employerId: 316119,
      employerName: "G2 Legal Limited",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Insolvency Solicitor",
      locationName: "Central London",
      minimumSalary: 55000,
      maximumSalary: 65000,
      currency: "GBP",
      expirationDate: "11/12/2019",
      date: "13/11/2019",
      jobDescription:
        "A fantastic opportunity has arisen for a junior insolvency solicitor to join a highly regarded full-service firm in their central London office.As an insolvency solicitor, you will be joining a small team of 1 partner and 2 associates who act on behalf of clients including insolvency practitioners, creditors, companies, directors and other stakeholders in both formal insolvencies and financially distressed  situations.You... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/insolvency-solicitor/39358588"
    },
    {
      jobId: 39296752,
      employerId: 344195,
      employerName: "Frazer Jones",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "HR Business Partner",
      locationName: "London",
      minimumSalary: 50000,
      maximumSalary: 60000,
      currency: "GBP",
      expirationDate: "17/12/2019",
      date: "05/11/2019",
      jobDescription:
        " The job of HR Business Partner will deliver ER and policy advice and be out in the business, partnering senior stakeholders. You will build strong relationships with your client group and get out in the business as well as work closely with your HR peers.  In order to apply you must have excellent communications skills - particularly written as this is the kind of environment where details matter, the cleitn group is highly accademic.... ",
      applications: 26,
      jobUrl: "https://www.reed.co.uk/jobs/hr-business-partner/39296752"
    },
    {
      jobId: 39142207,
      employerId: 243032,
      employerName: "Carlton Recruitment",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Coordinator",
      locationName: "Hampton Court",
      minimumSalary: 14400,
      maximumSalary: 14400,
      currency: "GBP",
      expirationDate: "13/12/2019",
      date: "15/10/2019",
      jobDescription:
        " Coordinator Hampton &#163;14,400 Part-Time Permanent - 21 hours per week - days/hours to suit Our award winning client based in Hampton is seeking a Coordinator with excellent customer service and database experience to join their team! The purpose of the role will be to ensure an excellent and efficient service to customers, making them feel valu... ",
      applications: 19,
      jobUrl: "https://www.reed.co.uk/jobs/coordinator/39142207"
    },
    {
      jobId: 39358587,
      employerId: 540194,
      employerName: "Mason & Wake",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle:
        "Business Development Manager- HR Software £80,000 + £80,000 OTE uncapped UK",
      locationName: "West London",
      minimumSalary: 75000,
      maximumSalary: 85000,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " Business Development - HR Software &#163;80,000 &#43; &#163;80,000 OTE uncapped London  Our client is a market leading provider of end to end software solutions for HR departments. Established across the U.K and EMEA, they are currently looking for a Business Development representative to join the team. The successful candidate will be responsible for a 360’ sales cycle; managing and gr... ",
      applications: 0,
      jobUrl:
        "https://www.reed.co.uk/jobs/business-development-manager-hr-software-80000--80000-ote-uncapped-uk/39358587"
    },
    {
      jobId: 39296751,
      employerId: 428851,
      employerName: "Pier Recruitment",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Warehouse Assistant",
      locationName: "Uckfield",
      minimumSalary: 8.21,
      maximumSalary: 8.21,
      currency: "GBP",
      expirationDate: "19/11/2019",
      date: "05/11/2019",
      jobDescription:
        " We are currently recruiting for a Warehouse Assistant within a large printing room. Location: UCKFIELD Position: Temporary (Ad hoc work) This is an on-going temporary role through Pier Recruitment, you will be handling boxes, packing them back up once printed. Supporting the printers in setting up the print run, de lidding the boxes and supporting the Print operators with general warehouse duties.If ... ",
      applications: 8,
      jobUrl: "https://www.reed.co.uk/jobs/warehouse-assistant/39296751"
    },
    {
      jobId: 39274401,
      employerId: 391063,
      employerName: "Opus Recruitment Solutions Ltd",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Network Security Specialist",
      locationName: "Maidenhead",
      minimumSalary: 50000,
      maximumSalary: 55000,
      currency: "GBP",
      expirationDate: "15/11/2019",
      date: "01/11/2019",
      jobDescription:
        "Network Security Specialist /&nbsp;&#163;50,000 - &#163;55,000 / MaidenheadKey Skills:&nbsp;Cisco, IPSEC, Virtualisation, Switches, Network SecurityThis Infrastructure Security Engineer role is an excellent opportunity to join an award winning SaaS provider in their Maidenhead branch.Since their inception they have gained a great reputation as the go to service provider in their industry, getting recognition a... ",
      applications: 2,
      jobUrl: "https://www.reed.co.uk/jobs/network-security-specialist/39274401"
    },
    {
      jobId: 39296750,
      employerId: 602263,
      employerName: "Fyte",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Administrator - 3 month FTC",
      locationName: "Glasgow",
      minimumSalary: null,
      maximumSalary: null,
      currency: null,
      expirationDate: "05/12/2019",
      date: "05/11/2019",
      jobDescription:
        " Company description: Morgan Philips Group is an innovative recruitment business with a footprint across 4 continents. In just 5 years, we have built a global platform that disrupts conventional thinking in executive and professional recruiting. We combine high-touch consultancy  with worldwide search capability and digital sourcing technologies to help you recruit better, faster and cost effectively. <br... ",
      applications: 8,
      jobUrl: "https://www.reed.co.uk/jobs/administrator-3-month-ftc/39296750"
    },
    {
      jobId: 39274400,
      employerId: 602263,
      employerName: "Fyte",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Marketing and Business Development Executive",
      locationName: "Edinburgh",
      minimumSalary: null,
      maximumSalary: null,
      currency: null,
      expirationDate: "01/12/2019",
      date: "01/11/2019",
      jobDescription:
        " Company description: Morgan Philips Group is an innovative recruitment business with a footprint across 4 continents. In just 5 years, we have built a global platform that disrupts conventional thinking in executive and professional recruiting. We combine high-touch consultancy  with worldwide search capability and digital sourcing technologies to help you recruit better, faster and cost effectively. Job de... ",
      applications: 3,
      jobUrl:
        "https://www.reed.co.uk/jobs/marketing-and-business-development-executive/39274400"
    },
    {
      jobId: 39225205,
      employerId: 447583,
      employerName: "Pendragon PLC",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Service Technician",
      locationName: "Hamilton",
      minimumSalary: null,
      maximumSalary: null,
      currency: null,
      expirationDate: "06/12/2019",
      date: "25/10/2019",
      jobDescription:
        " Do you have experience in engine repair and minor mechanical repairs alongside general servicing repairs? Do you have an NVQ Level 2/3 or equivalent? We’re looking for a Service Technician / Mechanic to join the team, from a variety of backgrounds including Prestige/Volume Franchised Dealers or an Independent garage. To be a Service Technician/Mechanic with us, you will require a Full UK drivers’ licence, NVQ Level 2/3 or equiv... ",
      applications: 3,
      jobUrl: "https://www.reed.co.uk/jobs/service-technician/39225205"
    },
    {
      jobId: 39358586,
      employerId: 561913,
      employerName: "Randstad Construction, Property and Engineering",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Temp Helpdesk / Admin",
      locationName: "City of London",
      minimumSalary: 12,
      maximumSalary: 13,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " Helpdesk/Administrator -Heart of London - Temp  The ideal candidate will be immediately available and able to start at short notice. You will require an understanding of administration with a proven track record in offices or any other commercial site. Working as part of an administration team that is commitment to excellence and offering maximum flexibility in supporting the contract across the full spectrum o... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/temp-helpdesk-admin/39358586"
    },
    {
      jobId: 39358585,
      employerId: 524744,
      employerName: "Hays Specialist Recruitment Limited",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Partner Designate",
      locationName: "Bristol",
      minimumSalary: 50000,
      maximumSalary: 60000,
      currency: "GBP",
      expirationDate: "11/12/2019",
      date: "13/11/2019",
      jobDescription:
        " Partner Designate, Bristol, &#163;50,000 - &#163;60,000 A rare opportunity exists for an experienced chartered accountant to join a leading accountancy practice as Partner Designate.The firm has already seen growth both organically and through acquisition and are now ready for their next stage of growth by the introduction  of a Partner Designate.Working closely with the existing Partners, as Partner Designate you wil... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/partner-designate/39358585"
    },
    {
      jobId: 37782408,
      employerId: 532061,
      employerName: "Marc Brunel Limited",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Panel Technician ",
      locationName: "Steeple Aston",
      minimumSalary: null,
      maximumSalary: null,
      currency: null,
      expirationDate: "25/12/2019",
      date: "17/04/2019",
      jobDescription:
        " Our client is a classic and vintage car restoration company located near Bicester, Oxfordshire with more than 40 years’ experience in vehicle restoration. They are actively recruiting for a fully skilled panel beater/fabricator with traditional skills, and patience, to join our growing team in the restoration and repair of classic and vintage vehicles. You will be carrying out full restorations which include services such as we... ",
      applications: 4,
      jobUrl: "https://www.reed.co.uk/jobs/panel-technician/37782408"
    },
    {
      jobId: 39296749,
      employerId: 575264,
      employerName: "REED",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Functional Assessor Physiotherapist",
      locationName: "Bristol",
      minimumSalary: 38760,
      maximumSalary: 38760,
      currency: "GBP",
      expirationDate: "05/12/2019",
      date: "05/11/2019",
      jobDescription:
        " Are you a qualified Physiotherapist looking for balanced work, Monday to Friday 9am-5pm, with NO unpredictable shift patterns? Are you looking to make an exciting career move away from the NHS? Would you like to earn &#163;38,760 - &#163;45,390pa…plus benefits? REED Specialist Recruitment has partnered with a private organisation who specialise in carrying out disability... ",
      applications: 1,
      jobUrl:
        "https://www.reed.co.uk/jobs/functional-assessor-physiotherapist/39296749"
    },
    {
      jobId: 39274399,
      employerId: 418296,
      employerName: "Gi Group",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Telephone Interviewer - IMMEDIATE START",
      locationName: "Edinburgh",
      minimumSalary: 8.25,
      maximumSalary: 8.25,
      currency: "GBP",
      expirationDate: "13/12/2019",
      date: "01/11/2019",
      jobDescription:
        " We are working on behalf of one of the market leaders in Market Research,  They require a number of customer service agent to work on a current campaign that is lasting 6 months No experience required, Immediate start, Flexible working hours available They are very flexible with working hours and can meet most candidate's expectations  * Full time* Part time * Weekend working  I... ",
      applications: 6,
      jobUrl:
        "https://www.reed.co.uk/jobs/telephone-interviewer-immediate-start/39274399"
    },
    {
      jobId: 39296748,
      employerId: 207638,
      employerName: "Equals One",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Field Service Engineer",
      locationName: "Dukinfield",
      minimumSalary: 8.21,
      maximumSalary: 8.21,
      currency: "GBP",
      expirationDate: "17/12/2019",
      date: "05/11/2019",
      jobDescription:
        " Field Service Engineer - starting salary &#163;8.21 ph Oldham &amp; Tameside area 45 hours pw Job purpose: To enable the Company to achieve the agreed contractual standard of service required by completing initial training in the workshop reconditioning wheelchairs to gain essential product knowledge. On completion of initial training this will en... ",
      applications: 1,
      jobUrl: "https://www.reed.co.uk/jobs/field-service-engineer/39296748"
    },
    {
      jobId: 39358584,
      employerId: 91973,
      employerName: "Wade Macdonald",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Data Insight Analyst",
      locationName: "Reading",
      minimumSalary: null,
      maximumSalary: null,
      currency: null,
      expirationDate: "11/12/2019",
      date: "13/11/2019",
      jobDescription:
        " Data Insights Analyst - Reading The company I am currently representing a Blue Chip Organisation that deals with large and varied data sets in the utilities sector. They are looking for a Data analyst to provide accurate insights by combining predictive analytics and marketing campaigns to improve  their outputs across multiple functions within the business. This is a great opportunity to join one of the largest companies in th... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/data-insight-analyst/39358584"
    },
    {
      jobId: 39296747,
      employerId: 524744,
      employerName: "Hays Specialist Recruitment Limited",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Finance Assistant",
      locationName: "Pontypool",
      minimumSalary: 10,
      maximumSalary: 12,
      currency: "GBP",
      expirationDate: "17/12/2019",
      date: "05/11/2019",
      jobDescription:
        " Temporary Finance Assistant - Pontypool Your new companyYour new organisation operate within the public sector and are looking for an experienced finance assistant to assist with their current workload for around 2-3 months. Your new roleYou will be responsible for maintaining the cashbook, reconciling control accounts in the balance sheet, assisting with the implementatio... ",
      applications: 2,
      jobUrl: "https://www.reed.co.uk/jobs/finance-assistant/39296747"
    },
    {
      jobId: 39296746,
      employerId: 586712,
      employerName: "Plamo Trade limited",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Technical Asscociate - Vertical Transportation ",
      locationName: "Birmingham",
      minimumSalary: null,
      maximumSalary: null,
      currency: null,
      expirationDate: "17/12/2019",
      date: "05/11/2019",
      jobDescription:
        " A leading UK consultancy that provides building services engineering and sustainability solutions nationwide is looking to recruit a 'Technical Associate' (Vertical Transportation) for their Birmingham office. Essential Attributes: Ability to work on own initiative, manage and lead by example. Expected to build relationships with Clients, write clear and concise reports and case studies, present to Clients who ... ",
      applications: 1,
      jobUrl:
        "https://www.reed.co.uk/jobs/technical-asscociate-vertical-transportation/39296746"
    },
    {
      jobId: 39358583,
      employerId: 472689,
      employerName: "Page Personnel Finance",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Commercial Cost / Finance Analyst",
      locationName: "Sevenoaks",
      minimumSalary: 28000,
      maximumSalary: 35000,
      currency: "GBP",
      expirationDate: "20/11/2019",
      date: "13/11/2019",
      jobDescription:
        " The Cost Modeller is a key role in the Business Development Team within the Division. The long-term nature of the contracts necessitates an accurate assessment of a wide range of costs and outputs to accurately assess the final price to submit to a client  as part of a complex tendering exercise. Client Details A well established successful organisation looking to expand their Finance and Business Development t... ",
      applications: 0,
      jobUrl:
        "https://www.reed.co.uk/jobs/commercial-cost-finance-analyst/39358583"
    },
    {
      jobId: 39358582,
      employerId: 618594,
      employerName: "Furniture Enterprises Ltd",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Office Junior",
      locationName: "Kelvedon",
      minimumSalary: 6.15,
      maximumSalary: 8.21,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " Candidate must be able to drive due to location. We are a small family run manufacturing business that is currently expanding and are looking for a fun, energetic, hard working and eager to learn individual. Must be computer literate and have a qualification in English. Basic skills in Office i.e. word, powerpoint, outlook, excel. Good knowledge and skills of Facebook, instagram, and twitter. <b... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/office-junior/39358582"
    },
    {
      jobId: 39296745,
      employerId: 384855,
      employerName: "Advancing People",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Senior Sales Executive",
      locationName: "Royston",
      minimumSalary: 22000,
      maximumSalary: 24000,
      currency: "GBP",
      expirationDate: "03/12/2019",
      date: "05/11/2019",
      jobDescription:
        " Advancing People have a good opportunity for a Senior Sales Executive for a leading publishers within the care sector. As a Senior Sales Executive you will need to help maximise sales. The suitable candidate will be joining an established and dynamic team. The ideal candidate will have relevant sales experience and a driven personality in order to be successful within the  organisation. Key responsibili... ",
      applications: 3,
      jobUrl: "https://www.reed.co.uk/jobs/senior-sales-executive/39296745"
    },
    {
      jobId: 39358581,
      employerId: 618588,
      employerName: "The People Collection",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Accounts Payable Assistant",
      locationName: "West London",
      minimumSalary: 25000,
      maximumSalary: 30000,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " To provide administrative support to the Financial Controller, undertaking clerical tasks such as typing, filing, making phone calls, handling mail and bookkeeping to help maintain the office and keep it running smoothly. To liaise with internal and external  stakeholders. Responsibilities:  All aspects of accounts payable for multi-currency suppliersInvoice processingSupplier statement r... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/accounts-payable-assistant/39358581"
    },
    {
      jobId: 39274398,
      employerId: 496044,
      employerName: "CastleView Group ",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Picker & Packer ",
      locationName: "Wednesbury",
      minimumSalary: 8.45,
      maximumSalary: 8.45,
      currency: "GBP",
      expirationDate: "13/12/2019",
      date: "01/11/2019",
      jobDescription:
        " Overview  Our Client is Keeping over 600 UK stores fully stocked (no small task.) That’s the job of our warehouses, matching supply and demand 24/7. With goods of all kinds flowing in and out, it’s essential that they are received, stored and delivered on time and  in excellent condition. If you enjoy being part of a friendly team buzzing with non-stop activity, this is the place for you Job Responsibil... ",
      applications: 37,
      jobUrl: "https://www.reed.co.uk/jobs/picker-packer/39274398"
    },
    {
      jobId: 39296744,
      employerId: 316614,
      employerName: "Faith Recruitment",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Sales Administrator",
      locationName: "Weybridge",
      minimumSalary: 20000,
      maximumSalary: 24000,
      currency: "GBP",
      expirationDate: "03/12/2019",
      date: "05/11/2019",
      jobDescription:
        " Sales Administrator Weybridge &#163;20-24k Temp to perm My client in Weybridge are seeking a Sales Administrator to join their ever growing team. You will be supporting the sales team by communicating with existing customers regarding quotes in line with customer needs. Responsibilities include Liaise with customer regarding their business needs Answer calls and respond to customer emails ... ",
      applications: 6,
      jobUrl: "https://www.reed.co.uk/jobs/sales-administrator/39296744"
    },
    {
      jobId: 39274396,
      employerId: 524744,
      employerName: "Hays Specialist Recruitment Limited",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Senior Manager Tax Investigations",
      locationName: "London",
      minimumSalary: null,
      maximumSalary: null,
      currency: null,
      expirationDate: "13/12/2019",
      date: "01/11/2019",
      jobDescription:
        " Tax Senior Manager Jobs, Tax Investigations Jobs, Senior Manager Tax Investigations Jobs, London Tax Jobs.Your new companyWell established tax boutique based in Central London.Your new roleMy client works with individuals, companies and offshore structures in dealing with HMRC Investigations.Due to continued and ongoing growth they are now looking t... ",
      applications: 1,
      jobUrl:
        "https://www.reed.co.uk/jobs/senior-manager-tax-investigations/39274396"
    },
    {
      jobId: 39358580,
      employerId: 373440,
      employerName: "P3 Search & Selection",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Digital Marketing Manager",
      locationName: "Staffordshire",
      minimumSalary: 30000,
      maximumSalary: 40000,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " Our client is the UK's leading manufacturer or homeware, tableware and catering equipment products distributing globally. Due to their fantastic growth they are now seeking to recruit a Digital Marketing Manager. The role;  Develop and implement digital marketing strategy with a focus on driving both brand awareness &amp; engagement and driving traffic to our websites to increase conversion, drive s... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/digital-marketing-manager/39358580"
    },
    {
      jobId: 39358579,
      employerId: 536652,
      employerName: "Bronson Resourcing",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Business Development Manager - German or French Speaking",
      locationName: "Bourne End",
      minimumSalary: 35000,
      maximumSalary: 55000,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " Our client has been providing market leading raw price data at a global level for over thirty years. Due to growth, they now have an immediate requirement for a consultative Business Development Manager to work alongside marketing and the rest of the commercial team to expand the French and/or German client base. You will be expected to engage, prospect and ultimately meet with retailers, manufacturers, financial institutions a... ",
      applications: 0,
      jobUrl:
        "https://www.reed.co.uk/jobs/business-development-manager-german-or-french-speaking/39358579"
    },
    {
      jobId: 39274395,
      employerId: 11488,
      employerName: "Centre People",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Logistics Administrator - Spanish Speaking",
      locationName: "North West London",
      minimumSalary: 23000,
      maximumSalary: 27000,
      currency: "GBP",
      expirationDate: "13/12/2019",
      date: "01/11/2019",
      jobDescription:
        " Logistics Administrator - Spanish Speaking  A long established international trading and logistics company with a wide and diverse range of food commodity products has a newly created role for a Spanish speaking individual with a background in contracts/logistics administration. Key responsibilities:  Execution of contracts to include liaising with suppliers and customers for gettin... ",
      applications: 45,
      jobUrl:
        "https://www.reed.co.uk/jobs/logistics-administrator-spanish-speaking/39274395"
    },
    {
      jobId: 39296743,
      employerId: 45560,
      employerName: "Better Prospects",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Housing Officer",
      locationName: "Aylesbury",
      minimumSalary: 18632,
      maximumSalary: 18632,
      currency: "GBP",
      expirationDate: "17/12/2019",
      date: "05/11/2019",
      jobDescription:
        " Are you looking for a rewarding role to help others? Our client a specialist charity are looking for a Housing Management Officer to join their small team to work with residents to ensure their tenancies are maintained and remain secure. The ideal candidate  will be someone who has previous experience and knowledge of Housing Benefits or in a Care based role. Key Responsibilities: - The Housing Management Offic... ",
      applications: 2,
      jobUrl: "https://www.reed.co.uk/jobs/housing-officer/39296743"
    },
    {
      jobId: 39358578,
      employerId: 377450,
      employerName: "Gabbott Recruitment Online Limited",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Head of Conveyancing",
      locationName: "Wigan",
      minimumSalary: 35000,
      maximumSalary: 40000,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " Head of Conveyancing Solicitor Conveyancing FCILEX Wigan area &#163;35,000 to &#163;40,000 plus negotiable, full time flexible working hours, free parking, plus great benefits Head of Conveyancing with residential property experience required for established and progressive firm of Solicitors busy and expanding department with exc... ",
      applications: 0,
      jobUrl: "https://www.reed.co.uk/jobs/head-of-conveyancing/39358578"
    },
    {
      jobId: 39274394,
      employerId: 426217,
      employerName: "Sacco Mann",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "RTA Litigator",
      locationName: "Leeds",
      minimumSalary: 28000,
      maximumSalary: 32000,
      currency: "GBP",
      expirationDate: "29/11/2019",
      date: "01/11/2019",
      jobDescription:
        " A top regional firm seeks a skilled Litigation fee earner to handle a caseload of Fast Track RTA files in central Leeds. My client is one of the UK's top providers of insurance and legal services within the industry and operate on a range of services with an ethical approach and the best possible advice and customer service. The firm seeks a candidate who can manage a fast track RTA caseload through all stages of investigation ... ",
      applications: 2,
      jobUrl: "https://www.reed.co.uk/jobs/rta-litigator/39274394"
    },
    {
      jobId: 39358577,
      employerId: 371499,
      employerName: "Exchange Street Financial Services",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Property Claims Technician / Adjuster Assistant",
      locationName: "Bristol",
      minimumSalary: 20000,
      maximumSalary: 25000,
      currency: "GBP",
      expirationDate: "11/12/2019",
      date: "13/11/2019",
      jobDescription:
        " Our client, a market leading Loss Adjusting Practice, is seeking to strengthen their team with the addition of a Property Claims Technician / Adjuster Executive to work out of their Bristol office. The successful candidate will be assisting in the handling  a portfolio of Domestic &amp; Commercial Property claims from notification until settlement, on behalf of prestigious clients. Typically, you will liaise with the Loss Adjusters, policyho... ",
      applications: 0,
      jobUrl:
        "https://www.reed.co.uk/jobs/property-claims-technician-adjuster-assistant/39358577"
    },
    {
      jobId: 38587493,
      employerId: 386963,
      employerName: "Blue Tree Recruits",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Digital Marketing Executive",
      locationName: "Shere",
      minimumSalary: 27000,
      maximumSalary: 30000,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "01/08/2019",
      jobDescription:
        " Do you have at least one year’s experience in digital marketing and social media? Are you interested in joining an ethical company focussed on health and wellbeing? This is a brand new role with tonnes of potential to make a huge contribution to an already very successful and growing business looking to significantly increase sales through a greater focus on its social media and web audience. You should have experience in writi... ",
      applications: 6,
      jobUrl: "https://www.reed.co.uk/jobs/digital-marketing-executive/38587493"
    },
    {
      jobId: 39358576,
      employerId: 416992,
      employerName: "Domus Recruitment Ltd",
      employerProfileId: null,
      employerProfileName: null,
      jobTitle: "Registered Manager Learning Disabilities/Mental Health",
      locationName: "Weston-super-Mare",
      minimumSalary: 30000,
      maximumSalary: 30000,
      currency: "GBP",
      expirationDate: "25/12/2019",
      date: "13/11/2019",
      jobDescription:
        " A great opportunity for a Registered Manager has arisen with a highly reputable national provider in Weston-Super-Mare, North Somerset.The service supports adults with a range of needs including mental health needs, ABI and learning disabilities. Individuals are supported to engage in their local community and to learn and practice new skills in a supported environment. They are paying up to &#163;30,000 for the succe... ",
      applications: 0,
      jobUrl:
        "https://www.reed.co.uk/jobs/registered-manager-learning-disabilities-mental-health/39358576"
    }
  ],
  ambiguousLocations: [],
  totalResults: 254266
};
